// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-8cfyhWHkUFG0gq05m2GM-EDYVKiUEY',
    appId: '1:641871048211:web:d5ec373cfba2fdcf28d9e6',
    messagingSenderId: '641871048211',
    projectId: 'zebra-minesweeper',
    authDomain: 'zebra-minesweeper.firebaseapp.com',
    storageBucket: 'zebra-minesweeper.appspot.com',
    measurementId: 'G-4HW4PYHCLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAi3Dpvc4gE6aJJnsiXJeVI4MbSJSYos',
    appId: '1:641871048211:android:7d9b8514dd86617628d9e6',
    messagingSenderId: '641871048211',
    projectId: 'zebra-minesweeper',
    storageBucket: 'zebra-minesweeper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrXFzSfqPVjNPh4oBgtdn645dhL_9rWE',
    appId: '1:641871048211:ios:76fde269590574ab28d9e6',
    messagingSenderId: '641871048211',
    projectId: 'zebra-minesweeper',
    storageBucket: 'zebra-minesweeper.appspot.com',
    iosClientId: '641871048211-5ssi71jica98edao7j2q0jqikkg3evoe.apps.googleusercontent.com',
    iosBundleId: 'xyz.zebracrypto.minesweeper',
  );
}
